package game;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import client.Client;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * Login_page'de rakip bulunana kadar bu sayfa açılmamalı.
 *
 * @author iremayvaz
 */
public class Game extends javax.swing.JFrame {

    public static Game game;
    public static Map map;
    public static Dice dice;

    public static Player oyuncu;
    public static boolean isYourTurn; // sıra benim mi

    public static Player rakip;

    public static ArrayList<Territory> secilenBolgeler = new ArrayList<>(); // buton selected

    public Game() throws IOException {
        initComponents();
    }

    public Game(ArrayList<Territory> gelenHarita) throws IOException {
        initComponents();
        // en başta sadece attack yapabilsin
        // yapmiyorsa skip edebilir.
        comboBox_moveTroops.setVisible(false);
        btn_deploy.setVisible(false);

        Game.game = this;
        Game.map = new Map();
        Game.map.all_territories = gelenHarita;

        System.out.println("Benim oyuncu id: " + Game.oyuncu.id);

        // Territory'leri butonlarla eşle
        for (Territory t : gelenHarita) {
            switch (t.name) {
                case "Afrika":
                    t.setButton(btn_afrika);
                    break;
                case "Asya":
                    t.setButton(btn_asya);
                    break;
                case "Avrupa":
                    t.setButton(btn_avrupa);
                    break;
                case "Avustralya":
                    t.setButton(btn_avustralya);
                    break;
                case "Güney Amerika":
                    t.setButton(btn_guneyAmerika);
                    break;
                case "Kuzey Amerika":
                    t.setButton(btn_kuzeyAmerika);
                    break;
            }

        }

        // Territory'leri oyuncularla eşle
        for (Territory t : gelenHarita) {
            if (t.playerID == Game.oyuncu.id) { // her oyuncu kendi bölgelerini görmeli
                Game.oyuncu.territories.add(t);
                t.owner = Game.oyuncu;
                t.bolge_butonu.setForeground(Color.green); // kendi bölgeleri yeşil
            } else {
                Game.rakip.territories.add(t);
                t.owner = Game.rakip;
                t.bolge_butonu.setForeground(Color.red); // rakip bölgeler kırmızı
            }
        }

        // Bölgelerin asker sayılarını frame'de göster
        for (Territory t : Game.map.all_territories) {
            t.bolge_butonu.setText(String.valueOf(t.totalTroop));
        }

        // Bölge seçimleri için
        for (Territory t : Game.map.all_territories) {
            t.bolge_butonu.addActionListener(e -> {
                // daha hic bolge secilmedi
                if (Game.secilenBolgeler.isEmpty()) { 
                    // ilk secim kendi bölgesi olmalı
                    if (t.playerID == Game.oyuncu.id && t.totalTroop > 1) { 
                        Game.secilenBolgeler.add(t);
                        t.bolge_butonu.setSelected(false);
                    } else {
                        t.bolge_butonu.setSelected(false);
                        JOptionPane.showMessageDialog(pnl_harita, "FIRST SELECT FROM YOUR TERRITORIES"
                                + "\nWHICH HAS MORE THAN 1 TROOP!",
                                "WARNING", JOptionPane.WARNING_MESSAGE);
                    }
                // 2. bölge karşıdan olsun
                } else if (Game.secilenBolgeler.size() == 1) { 
                    if (t.playerID != Game.oyuncu.id) {
                        Game.secilenBolgeler.add(t);
                        t.bolge_butonu.setSelected(false);
                    } else {
                        t.bolge_butonu.setSelected(false);
                        JOptionPane.showMessageDialog(pnl_harita, "SELECT FROM OPPONENT'S TERRITORIES!",
                                "WARNING", JOptionPane.WARNING_MESSAGE);
                    }
                // 2 den fazla seçilemez
                } else { 
                    t.bolge_butonu.setSelected(false);
                    JOptionPane.showMessageDialog(pnl_harita, "YOU CANNOT SELECT MORE THAN 2 TERRITORY TO ATTACK!",
                            "WARNING", JOptionPane.WARNING_MESSAGE);
                }

            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pnl_harita = new javax.swing.JPanel();
        lbl_you = new javax.swing.JLabel();
        lbl_localClient = new javax.swing.JLabel();
        lbl_opponent = new javax.swing.JLabel();
        lbl_otherClient = new javax.swing.JLabel();
        lbl_state = new javax.swing.JLabel();
        comboBox_moveTroops = new javax.swing.JComboBox<>();
        btn_asya = new javax.swing.JToggleButton();
        btn_avustralya = new javax.swing.JToggleButton();
        btn_avrupa = new javax.swing.JToggleButton();
        btn_afrika = new javax.swing.JToggleButton();
        btn_kuzeyAmerika = new javax.swing.JToggleButton();
        btn_guneyAmerika = new javax.swing.JToggleButton();
        btn_attack = new javax.swing.JToggleButton();
        btn_deploy = new javax.swing.JToggleButton();
        btn_skip = new javax.swing.JToggleButton();
        lbl_harita = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_harita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_you.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_you.setForeground(new java.awt.Color(255, 255, 255));
        lbl_you.setText("YOU :");
        pnl_harita.add(lbl_you, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 40));

        lbl_localClient.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_localClient.setForeground(new java.awt.Color(0, 255, 0));
        pnl_harita.add(lbl_localClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 120, 40));

        lbl_opponent.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_opponent.setForeground(new java.awt.Color(255, 255, 255));
        lbl_opponent.setText(": OPPONENT");
        pnl_harita.add(lbl_opponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 30, 120, 40));

        lbl_otherClient.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_otherClient.setForeground(new java.awt.Color(255, 0, 0));
        pnl_harita.add(lbl_otherClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 27, 130, 40));

        lbl_state.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_state.setForeground(new java.awt.Color(255, 255, 255));
        pnl_harita.add(lbl_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 190, 30));

        comboBox_moveTroops.setBackground(new java.awt.Color(0, 51, 255));
        comboBox_moveTroops.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        comboBox_moveTroops.setForeground(new java.awt.Color(255, 255, 255));
        pnl_harita.add(comboBox_moveTroops, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 80, -1));

        btn_asya.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_asya.setForeground(new java.awt.Color(255, 255, 255));
        btn_asya.setText("0");
        btn_asya.setBorder(null);
        btn_asya.setBorderPainted(false);
        btn_asya.setContentAreaFilled(false);
        btn_asya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_asya.setFocusPainted(false);
        pnl_harita.add(btn_asya, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 170, 210));

        btn_avustralya.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_avustralya.setForeground(new java.awt.Color(255, 255, 255));
        btn_avustralya.setText("0");
        btn_avustralya.setBorder(null);
        btn_avustralya.setBorderPainted(false);
        btn_avustralya.setContentAreaFilled(false);
        btn_avustralya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_avustralya, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, 140, 100));

        btn_avrupa.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_avrupa.setForeground(new java.awt.Color(255, 255, 255));
        btn_avrupa.setText("0");
        btn_avrupa.setBorder(null);
        btn_avrupa.setBorderPainted(false);
        btn_avrupa.setContentAreaFilled(false);
        btn_avrupa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_avrupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 270, 200));

        btn_afrika.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_afrika.setForeground(new java.awt.Color(255, 255, 255));
        btn_afrika.setText("0");
        btn_afrika.setBorder(null);
        btn_afrika.setBorderPainted(false);
        btn_afrika.setContentAreaFilled(false);
        btn_afrika.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_afrika, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 150, 190));

        btn_kuzeyAmerika.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_kuzeyAmerika.setForeground(new java.awt.Color(255, 255, 255));
        btn_kuzeyAmerika.setText("0");
        btn_kuzeyAmerika.setBorder(null);
        btn_kuzeyAmerika.setBorderPainted(false);
        btn_kuzeyAmerika.setContentAreaFilled(false);
        btn_kuzeyAmerika.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_kuzeyAmerika, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 210, 240));

        btn_guneyAmerika.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_guneyAmerika.setForeground(new java.awt.Color(255, 255, 255));
        btn_guneyAmerika.setText("0");
        btn_guneyAmerika.setBorder(null);
        btn_guneyAmerika.setBorderPainted(false);
        btn_guneyAmerika.setContentAreaFilled(false);
        btn_guneyAmerika.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_guneyAmerika, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 160, 240));

        btn_attack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_attack.setForeground(new java.awt.Color(153, 204, 255));
        btn_attack.setText("ATTACK");
        btn_attack.setBorder(null);
        btn_attack.setBorderPainted(false);
        btn_attack.setContentAreaFilled(false);
        btn_attack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attackActionPerformed(evt);
            }
        });
        pnl_harita.add(btn_attack, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, -1, -1));

        btn_deploy.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_deploy.setForeground(new java.awt.Color(153, 204, 255));
        btn_deploy.setText("DEPLOY");
        btn_deploy.setBorder(null);
        btn_deploy.setBorderPainted(false);
        btn_deploy.setContentAreaFilled(false);
        btn_deploy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_deploy, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, -1, -1));

        btn_skip.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_skip.setForeground(new java.awt.Color(204, 204, 204));
        btn_skip.setText("SKIP");
        btn_skip.setBorder(null);
        btn_skip.setBorderPainted(false);
        btn_skip.setContentAreaFilled(false);
        btn_skip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_skip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_skipActionPerformed(evt);
            }
        });
        pnl_harita.add(btn_skip, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 400, 80, -1));

        lbl_harita.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        lbl_harita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/harita.png"))); // NOI18N
        pnl_harita.add(lbl_harita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_harita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_harita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_attackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attackActionPerformed
        //handleSelection();

        try {
            Client.SendMessageToServer(new Message(Message.Type.ATTACK, Game.secilenBolgeler));
        } catch (IOException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Game.oyuncu.willAttack = false; // saldırdı bitti
        Game.secilenBolgeler.clear();
        btn_deploy.setVisible(true); // asker konuşlandırma aktif
        setComboboxVisible();
        btn_attack.setEnabled(false); // herkes 1 defa saldırabilir
    }//GEN-LAST:event_btn_attackActionPerformed

    private void btn_skipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_skipActionPerformed
        if (btn_skip.isSelected()) {
            try {
                this.isYourTurn = false;
                lbl_state.setText(rakip.name + "'s turn");
                btn_attack.setEnabled(true);

                Client.SendMessageToServer(new Message(Message.Type.SKIP_TURN, Game.oyuncu.id));
            } catch (IOException ex) {
                Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_skipActionPerformed

    // bölge seçimleri
    public void handleSelection() {
        if (!this.isYourTurn) { // sırası değilse
            JOptionPane.showMessageDialog(pnl_harita, "NOT YOUR TURN!",
                    "WARNING", JOptionPane.WARNING_MESSAGE);
        } else { // sırasıysa

            switch (this.secilenBolgeler.size()) {
                case 0:
                    JOptionPane.showMessageDialog(pnl_harita, "NO SELECTIONS TO ATTACK!",
                            "WARNING", JOptionPane.WARNING_MESSAGE);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(pnl_harita, "SELECT ONE MORE TO ATTACK!",
                            "WARNING", JOptionPane.WARNING_MESSAGE);
                    break;
                case 2:
                    Territory saldiran = this.secilenBolgeler.get(0);
                    System.out.println("saldıran : " + saldiran.name);
                    Territory savunan = this.secilenBolgeler.get(1);
                    System.out.println("savunan : " + savunan.name);
                    break;

            }

            if (this.secilenBolgeler.size() > 3) {
                JOptionPane.showMessageDialog(pnl_harita, "YOU CANNOT SELECT MORE THAN 2 TERRITORY TO ATTACK!",
                        "WARNING", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    public JToggleButton getTerritoryByButton(String bolgeAdi) { // Bölge butonlarını bulma
        for (Territory t : Game.map.all_territories) {
            if (t.name.equals(bolgeAdi)) {
                return t.bolge_butonu;
            }
        }
        return null;
    }

    public void setComboboxVisible() {
        if (btn_deploy.isSelected()) { // asker konuşlandırmak istiyorsam 
            comboBox_moveTroops.setVisible(true); // combobox görünür olsun
        }
    }

    public void readyToAttack() {
        if (lbl_state.getText() == "YOUR TURN") {
            Game.oyuncu.willAttack = true;

        } else { // sıra bende değilse ekrana dokunamam
            for (Territory t : Game.map.all_territories) {
                t.getBolge_butonu().setEnabled(false);
            }
            btn_attack.setEnabled(false);
            btn_deploy.setEnabled(false);
            btn_skip.setEnabled(false);
            JOptionPane.showMessageDialog(null, "NOT YOUR TURN", "UYARI", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Game().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_afrika;
    private javax.swing.JToggleButton btn_asya;
    private javax.swing.JToggleButton btn_attack;
    private javax.swing.JToggleButton btn_avrupa;
    private javax.swing.JToggleButton btn_avustralya;
    private javax.swing.JToggleButton btn_deploy;
    private javax.swing.JToggleButton btn_guneyAmerika;
    private javax.swing.JToggleButton btn_kuzeyAmerika;
    private javax.swing.JToggleButton btn_skip;
    private javax.swing.JComboBox<Integer> comboBox_moveTroops;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl_harita;
    public javax.swing.JLabel lbl_localClient;
    private javax.swing.JLabel lbl_opponent;
    public javax.swing.JLabel lbl_otherClient;
    public javax.swing.JLabel lbl_state;
    private javax.swing.JLabel lbl_you;
    private javax.swing.JPanel pnl_harita;
    // End of variables declaration//GEN-END:variables
}
