/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project1.game_ui;

/**
 *
 * @author iremayvaz
 */
public class Game_page extends javax.swing.JFrame {

    /**
     * Creates new form Game_page
     */
    public Game_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_game = new javax.swing.JPanel();
        pnl_bolge1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pnl_bolge2 = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        pnl_bolge3 = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        pnl_bolge4 = new javax.swing.JPanel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        pnl_bolge5 = new javax.swing.JPanel();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_game.setBackground(new java.awt.Color(70, 181, 242));

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout pnl_bolge1Layout = new javax.swing.GroupLayout(pnl_bolge1);
        pnl_bolge1.setLayout(pnl_bolge1Layout);
        pnl_bolge1Layout.setHorizontalGroup(
            pnl_bolge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bolge1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_bolge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_bolge1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton4))
                    .addGroup(pnl_bolge1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton1))
                    .addGroup(pnl_bolge1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_bolge1Layout.setVerticalGroup(
            pnl_bolge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bolge1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_bolge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jButton23.setText("jButton1");

        jButton24.setText("jButton2");

        jButton25.setText("jButton3");

        jButton26.setText("jButton4");

        javax.swing.GroupLayout pnl_bolge2Layout = new javax.swing.GroupLayout(pnl_bolge2);
        pnl_bolge2.setLayout(pnl_bolge2Layout);
        pnl_bolge2Layout.setHorizontalGroup(
            pnl_bolge2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bolge2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_bolge2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_bolge2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton26))
                    .addGroup(pnl_bolge2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton23))
                    .addGroup(pnl_bolge2Layout.createSequentialGroup()
                        .addComponent(jButton24)
                        .addGap(18, 18, 18)
                        .addComponent(jButton25)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_bolge2Layout.setVerticalGroup(
            pnl_bolge2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bolge2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_bolge2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton24)
                    .addComponent(jButton25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton26)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jButton27.setText("jButton1");

        jButton28.setText("jButton2");

        jButton29.setText("jButton3");

        jButton30.setText("jButton4");

        javax.swing.GroupLayout pnl_bolge3Layout = new javax.swing.GroupLayout(pnl_bolge3);
        pnl_bolge3.setLayout(pnl_bolge3Layout);
        pnl_bolge3Layout.setHorizontalGroup(
            pnl_bolge3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bolge3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_bolge3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_bolge3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton30))
                    .addGroup(pnl_bolge3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton27))
                    .addGroup(pnl_bolge3Layout.createSequentialGroup()
                        .addComponent(jButton28)
                        .addGap(18, 18, 18)
                        .addComponent(jButton29)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_bolge3Layout.setVerticalGroup(
            pnl_bolge3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bolge3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_bolge3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton28)
                    .addComponent(jButton29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton30)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jButton31.setText("jButton1");

        jButton32.setText("jButton2");

        jButton33.setText("jButton3");

        jButton34.setText("jButton4");

        javax.swing.GroupLayout pnl_bolge4Layout = new javax.swing.GroupLayout(pnl_bolge4);
        pnl_bolge4.setLayout(pnl_bolge4Layout);
        pnl_bolge4Layout.setHorizontalGroup(
            pnl_bolge4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bolge4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_bolge4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_bolge4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton34))
                    .addGroup(pnl_bolge4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton31))
                    .addGroup(pnl_bolge4Layout.createSequentialGroup()
                        .addComponent(jButton32)
                        .addGap(18, 18, 18)
                        .addComponent(jButton33)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_bolge4Layout.setVerticalGroup(
            pnl_bolge4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bolge4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_bolge4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton32)
                    .addComponent(jButton33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton34)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jButton35.setText("jButton1");

        jButton36.setText("jButton2");

        jButton37.setText("jButton3");

        jButton38.setText("jButton4");

        javax.swing.GroupLayout pnl_bolge5Layout = new javax.swing.GroupLayout(pnl_bolge5);
        pnl_bolge5.setLayout(pnl_bolge5Layout);
        pnl_bolge5Layout.setHorizontalGroup(
            pnl_bolge5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bolge5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_bolge5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_bolge5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton38))
                    .addGroup(pnl_bolge5Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton35))
                    .addGroup(pnl_bolge5Layout.createSequentialGroup()
                        .addComponent(jButton36)
                        .addGap(18, 18, 18)
                        .addComponent(jButton37)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_bolge5Layout.setVerticalGroup(
            pnl_bolge5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bolge5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_bolge5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton36)
                    .addComponent(jButton37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton38)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jButton39.setText("jButton39");

        jButton40.setText("jButton40");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton39)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jButton40)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton40)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_gameLayout = new javax.swing.GroupLayout(pnl_game);
        pnl_game.setLayout(pnl_gameLayout);
        pnl_gameLayout.setHorizontalGroup(
            pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_gameLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(pnl_bolge2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addComponent(pnl_bolge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_gameLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(pnl_bolge4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_gameLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(pnl_bolge5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_gameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(pnl_bolge3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        pnl_gameLayout.setVerticalGroup(
            pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_gameLayout.createSequentialGroup()
                .addGroup(pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_gameLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(pnl_bolge2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_gameLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(pnl_bolge4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_gameLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(pnl_bolge3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_gameLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(pnl_bolge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_bolge5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_game, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_game, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnl_bolge1;
    private javax.swing.JPanel pnl_bolge2;
    private javax.swing.JPanel pnl_bolge3;
    private javax.swing.JPanel pnl_bolge4;
    private javax.swing.JPanel pnl_bolge5;
    private javax.swing.JPanel pnl_game;
    // End of variables declaration//GEN-END:variables
}
