/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author iremayvaz
 */
public class Game_page extends javax.swing.JFrame {

    /**
     * Creates new form Game_page
     */
    public Game_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_harita = new javax.swing.JPanel();
        btn_asia = new javax.swing.JButton();
        btn_avustralya = new javax.swing.JButton();
        btn_afrika = new javax.swing.JButton();
        btn_avrupa = new javax.swing.JButton();
        btn_kuzeyAmerika = new javax.swing.JButton();
        btn_guneyAmerika = new javax.swing.JButton();
        lbl_harita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_harita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_asia.setBackground(new java.awt.Color(0, 128, 0));
        btn_asia.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_asia.setForeground(new java.awt.Color(255, 255, 255));
        btn_asia.setText("1");
        btn_asia.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.green, java.awt.Color.blue));
        btn_asia.setContentAreaFilled(false);
        btn_asia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_asia.setFocusPainted(false);
        btn_asia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asiaActionPerformed(evt);
            }
        });
        pnl_harita.add(btn_asia, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 240, 300));

        btn_avustralya.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        btn_avustralya.setForeground(new java.awt.Color(255, 255, 255));
        btn_avustralya.setText("1");
        btn_avustralya.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.red, java.awt.Color.pink));
        btn_avustralya.setContentAreaFilled(false);
        pnl_harita.add(btn_avustralya, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 523, 120, 90));

        btn_afrika.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_afrika.setForeground(new java.awt.Color(255, 255, 255));
        btn_afrika.setText("1");
        btn_afrika.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.magenta, java.awt.Color.pink));
        btn_afrika.setContentAreaFilled(false);
        btn_afrika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_afrikaActionPerformed(evt);
            }
        });
        pnl_harita.add(btn_afrika, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 180, 220));

        btn_avrupa.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_avrupa.setForeground(new java.awt.Color(255, 255, 255));
        btn_avrupa.setText("1");
        btn_avrupa.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.pink, java.awt.Color.magenta));
        btn_avrupa.setContentAreaFilled(false);
        pnl_harita.add(btn_avrupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 260, 210));

        btn_kuzeyAmerika.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_kuzeyAmerika.setForeground(new java.awt.Color(255, 255, 255));
        btn_kuzeyAmerika.setText("1");
        btn_kuzeyAmerika.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.cyan, java.awt.Color.blue));
        btn_kuzeyAmerika.setContentAreaFilled(false);
        btn_kuzeyAmerika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kuzeyAmerikaActionPerformed(evt);
            }
        });
        pnl_harita.add(btn_kuzeyAmerika, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, 250));

        btn_guneyAmerika.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_guneyAmerika.setForeground(new java.awt.Color(255, 255, 255));
        btn_guneyAmerika.setText("1");
        btn_guneyAmerika.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.blue, java.awt.Color.magenta));
        btn_guneyAmerika.setContentAreaFilled(false);
        pnl_harita.add(btn_guneyAmerika, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 140, 260));

        lbl_harita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/harita.png"))); // NOI18N
        pnl_harita.add(lbl_harita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_harita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_harita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_asiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_asiaActionPerformed

    private void btn_kuzeyAmerikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kuzeyAmerikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_kuzeyAmerikaActionPerformed

    private void btn_afrikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_afrikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_afrikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_afrika;
    private javax.swing.JButton btn_asia;
    private javax.swing.JButton btn_avrupa;
    private javax.swing.JButton btn_avustralya;
    private javax.swing.JButton btn_guneyAmerika;
    private javax.swing.JButton btn_kuzeyAmerika;
    private javax.swing.JLabel lbl_harita;
    private javax.swing.JPanel pnl_harita;
    // End of variables declaration//GEN-END:variables
}
